name: Docker Build/Scan/Push

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-Scan-Push:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    env:
      IMAGE_REPO: jpecora/nix-foundation
      IMAGE_TAG: latest
      REGISTRY_ALIAS: j7p1o2r8
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::891376943487:role/Wiz-GitHub-jpecora-demos-pushECR
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build the latest Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t ${REGISTRY}/${REGISTRY_ALIAS}/${IMAGE_REPO}:${IMAGE_TAG} .
          echo "REGISTRY=${REGISTRY}/${REGISTRY_ALIAS}" >> "$GITHUB_ENV"


      - name: Download Wiz CLI
        run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

      - name: Authenticate to Wiz
        run: sudo -E ./wizcli auth

      - name: Run Wiz CLI image scan
        id: scan
        run: |-
          sudo -E ./wizcli docker scan -i ${REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG} --policy-hits-only --driver mountWithLayers \
          --dockerfile "./Dockerfile" --output wiz-output.json,sarif,true --tag github_action_run_id=${{ github.run_id }} \
          --sbom-format spdx-json --sbom-output-file sbom.json
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: wiz-output.json
          category: wiz

      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker push ${REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}

      - name: Run Wiz CLI image tag
        run: sudo -E ./wizcli docker tag -i ${REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}
